### ISSUE TITLE
Nu Html Checkerでエラーが出現する

### ISSUE THREAD

**Issue by momdo** [lv7777/w3c_cors#5]
https://validator.w3.org/nu/?doc=https%3A%2F%2Flv7777.github.io%2Fw3c_cors%2FCross-Origin%2520Resource%2520Sharing.htm

OmegaTをお使いのようですので、参考までに設定や機能に触れておくと、
- [設定]→[ファイルフィルター]→[設定（ボタン）]でファイルフィルターの設定を変えることができます。おそらく使っているだろう「HTML・XHTMLフィルター」が悪さをしているのかなと。
- [ツール]→[Check Issue for Current Document]で、OmegaTのタグの検査ができます。これでエラーの大半は除去できると思います。

**Comment by lv7777** [comment]
issueとさらに修正方法までありがとうございます！

探してみましたがそれっぽい所がありませんでした。

**Comment by lv7777** [comment]
ファイルフィルター　ー＞　`先頭と末尾のタグを削除`、`分節化しないプロジェクトから先頭と末尾の空白文字を削除`のチェックを両方外したところ、エラーの数は１になりましたが、翻訳が認識してくれなくなりますね。。。

**Comment by momdo** [comment]
[設定（ボタン）]というのは、下図の赤囲みになります。
![ファイルフィルター画面](https://cloud.githubusercontent.com/assets/8347177/21641861/e5bdb732-d2c1-11e6-8d27-0f9be7f9f010.png)

HTML・XHTMLフィルターを使用している場合にこのボタンを押すと、次のようなウインドウになるかと思います。
![default](https://cloud.githubusercontent.com/assets/8347177/21641899/248e818a-d2c2-11e6-9137-1e38f463d4c1.png)

**Comment by lv7777** [comment]
その辺を変えてみてもやはり翻訳が消えてしまいますね・・・

**Comment by momdo** [comment]
>先頭と末尾のタグを削除、分節化しないプロジェクトから先頭と末尾の空白文字を削除のチェックを両方外したところ、、エラーの数は１になりましたが、翻訳が認識してくれなくなりますね。。。

「消える」症状がどういったものなのか定かではありませんが、OmegaTのタグの数が変われば翻訳済みの文節が未翻訳扱いになるのはもっともなのかなと…。

**Comment by lv7777** [comment]
nu check editorの値を見ると全部`<code>`がunclosedになっています。
ですがすべての`<code>`がおかしいわけではなく一部の`<code>`が抜けてますね・・・

正規表現でなんとかできないかなと思ったのですが無理っぽいですね。

**Comment by lv7777** [comment]
> [ツール]→[Check Issue for Current Document]で、OmegaTのタグの検査ができます。これでエラーの大半は除去できると思います。

というのがどこのことを指しているのかわからないのですが教えていただけないでしょうか？

**Comment by lv7777** [comment]
ちなみに #6 に関してはこの問題が解決した後にやろうと思っています。

**Comment by momdo** [comment]
>>    [ツール]→[Check Issue for Current Document]で、OmegaTのタグの検査ができます。これでエラーの大半は除去できると思います。

>というのがどこのことを指しているのかわからないのですが教えていただけないでしょうか？

OmegaTのLatestだと私が最初に書いたものですが、OmegaT 3.5.2だと[ツール]→[タグ検証（現在の文書のみ）]でした。
「順序違い」は無視してもらっていいですが、「未使用」と出るものは修正する必要があります。文節の番号をクリックすればその文節に飛べます。

**Comment by lv7777** [comment]
できました。

> OmegaTのLatestだと私が最初に書いたものですが、OmegaT 3.5.2だと[ツール]→[タグ検証（現在の文書のみ）]でした。

タグ検証については #8 で修正済みで、それでもエラーが出てたのですが
nu validatorのissueでは`codeのinlineがなんとか`というエラーばかりだったので、順序違いによってcode要素の中にブロック属性のhtml要素が入ってしまって、手作業で96個全部直さないといけないのかなと思っていましたが、あるcode要素の閉じタグが`<c0>`のままで適切にパースされてなかったのがいけなかったようです。

この作業はfix_#5ブランチで行いました。

ありがとうございました。
