### ISSUE TITLE
W3CのIntellectual Rights FAQを満たせていない

### ISSUE THREAD

**Issue by momdo** [lv7777/w3c_cors#6]
<a href="https://www.w3.org/Consortium/Legal/IPR-FAQ-20000620#translate">May I translate a W3C Technical Report into another language?</a>によれば、

>In the translation, you must include the following information in the target language:
> 1 a reference to the original document
> 2 that the normative version of the specification is the English version found at the W3C site.
> 3 that the translated document may contain errors from the translation.

とあって、これらを満たさ**なければならない**とされます。（参考までに、たとえば<a href="https://momdo.github.io/css2/Overview.html">CSS2.2訳</a>の冒頭にある訳注は、これを満たすことを意図しています。）

**Comment by lv7777** [comment]
このissueはfix_#6ブランチで行っていましたが、
先ほど、fix_#6ブランチとmasterブランチをmergeしました。

このようになりました。fixed.
![screen shot 2017-01-08 at 23 43 32](https://cloud.githubusercontent.com/assets/8572307/21750688/7f46ee86-d5fc-11e6-833d-420af11f51a9.png)

issue報告ありがとうございました。
